/**
 * Danh sách thương hiệu + model dùng chung cho cả `/pricing` và `/listings/create`.
 * Khi cập nhật model mới chỉ cần sửa file này.
 */

export const BRANDS = [
  'Apple', 'Samsung', 'Xiaomi', 'OPPO', 'Vivo', 'Huawei', 'Realme', 'OnePlus',
  'Motorola', 'Sony', 'Nokia', 'Google', 'Honor', 'Nothing', 'RedMagic',
  'LG', 'ASUS', 'BKAV', 'Khác',
] as const;

export const PHONE_MODELS: Record<string, string[]> = {
  Apple: [
    // SE
    'iPhone SE (Thế hệ 1)', 'iPhone SE (Thế hệ 2)', 'iPhone SE (Thế hệ 3)',
    // Tiêu chuẩn
    'iPhone 6', 'iPhone 6 Plus', 'iPhone 6s', 'iPhone 6s Plus',
    'iPhone 7', 'iPhone 7 Plus',
    'iPhone 8', 'iPhone 8 Plus',
    'iPhone XR',
    'iPhone 11', 'iPhone 12', 'iPhone 12 mini',
    'iPhone 13', 'iPhone 13 mini',
    'iPhone 14', 'iPhone 14 Plus',
    'iPhone 15', 'iPhone 15 Plus',
    'iPhone 16', 'iPhone 16 Plus', 'iPhone 16e',
    'iPhone 17', 'iPhone 17e', 'iPhone Air',
    'iPhone 18',
    // Pro
    'iPhone X', 'iPhone XS', 'iPhone XS Max',
    'iPhone 11 Pro', 'iPhone 11 Pro Max',
    'iPhone 12 Pro', 'iPhone 12 Pro Max',
    'iPhone 13 Pro', 'iPhone 13 Pro Max',
    'iPhone 14 Pro', 'iPhone 14 Pro Max',
    'iPhone 15 Pro', 'iPhone 15 Pro Max',
    'iPhone 16 Pro', 'iPhone 16 Pro Max',
    'iPhone 17 Pro', 'iPhone 17 Pro Max',
    'iPhone 18 Pro', 'iPhone 18 Pro Max',
    // Đặc biệt
    'iPhone Fold',
    'Khác',
  ],
  Samsung: [
    'Galaxy S7', 'Galaxy S7 Edge',
    'Galaxy S8', 'Galaxy S8+',
    'Galaxy S9', 'Galaxy S9+',
    'Galaxy S10e', 'Galaxy S10', 'Galaxy S10+',
    'Galaxy S20', 'Galaxy S20+', 'Galaxy S20 Ultra', 'Galaxy S20 FE',
    'Galaxy S21', 'Galaxy S21+', 'Galaxy S21 Ultra', 'Galaxy S21 FE',
    'Galaxy S22', 'Galaxy S22+', 'Galaxy S22 Ultra',
    'Galaxy S23', 'Galaxy S23+', 'Galaxy S23 Ultra', 'Galaxy S23 FE',
    'Galaxy S24', 'Galaxy S24+', 'Galaxy S24 Ultra', 'Galaxy S24 FE',
    'Galaxy S25', 'Galaxy S25+', 'Galaxy S25 Ultra', 'Galaxy S25 FE', 'Galaxy S25 Edge',
    'Galaxy S26', 'Galaxy S26+', 'Galaxy S26 Ultra',
    'Galaxy Note 7', 'Galaxy Note 8', 'Galaxy Note FE',
    'Galaxy Note 9', 'Galaxy Note 10', 'Galaxy Note 10+',
    'Galaxy Note 20', 'Galaxy Note 20 Ultra',
    'Galaxy Fold', 'Galaxy Z Fold 2', 'Galaxy Z Fold 3', 'Galaxy Z Fold 4',
    'Galaxy Z Fold 5', 'Galaxy Z Fold 6', 'Galaxy Z Fold 7', 'Galaxy Z Fold 8',
    'Galaxy Z Fold SE',
    'Galaxy Z Flip', 'Galaxy Z Flip 3', 'Galaxy Z Flip 4', 'Galaxy Z Flip 5',
    'Galaxy Z Flip 6', 'Galaxy Z Flip 7', 'Galaxy Z Flip 7 FE', 'Galaxy Z Flip 8',
    'Galaxy Z TriFold',
    'Galaxy A10', 'Galaxy A20', 'Galaxy A30', 'Galaxy A40', 'Galaxy A50', 'Galaxy A70',
    'Galaxy A11', 'Galaxy A21', 'Galaxy A31', 'Galaxy A41', 'Galaxy A51', 'Galaxy A71',
    'Galaxy A12', 'Galaxy A22', 'Galaxy A32', 'Galaxy A52', 'Galaxy A72',
    'Galaxy A13', 'Galaxy A23', 'Galaxy A33', 'Galaxy A53', 'Galaxy A73',
    'Galaxy A14', 'Galaxy A24', 'Galaxy A34', 'Galaxy A54',
    'Galaxy A15', 'Galaxy A25', 'Galaxy A35', 'Galaxy A55',
    'Galaxy A16', 'Galaxy A17', 'Galaxy A36', 'Galaxy A37',
    'Galaxy A56 5G', 'Galaxy A57',
    'Galaxy M10', 'Galaxy M20', 'Galaxy M30', 'Galaxy M31', 'Galaxy M32',
    'Galaxy M33', 'Galaxy M52', 'Galaxy M53', 'Galaxy M54', 'Galaxy M55', 'Galaxy M56 5G',
    'Khác',
  ],
  Xiaomi: [
    'Mi 9', 'Mi 10', 'Mi 10 Pro', 'Mi 10 Ultra',
    'Mi 11', 'Mi 11 Pro', 'Mi 11 Ultra', 'Mi 11X',
    'Xiaomi 12', 'Xiaomi 12 Pro', 'Xiaomi 12 Ultra', 'Xiaomi 12S', 'Xiaomi 12S Pro', 'Xiaomi 12S Ultra',
    'Xiaomi 13', 'Xiaomi 13 Pro', 'Xiaomi 13 Ultra', 'Xiaomi 13T', 'Xiaomi 13T Pro',
    'Xiaomi 14', 'Xiaomi 14 Pro', 'Xiaomi 14 Ultra', 'Xiaomi 14T', 'Xiaomi 14T Pro',
    'Xiaomi 15', 'Xiaomi 15 Pro', 'Xiaomi 15 Ultra',
    'Xiaomi 17', 'Xiaomi 17 Ultra',
    'Xiaomi Civi 1', 'Xiaomi Civi 2', 'Xiaomi Civi 3', 'Xiaomi Civi 4 Pro',
    'Redmi Note 3', 'Redmi Note 4', 'Redmi Note 5', 'Redmi Note 5 Pro',
    'Redmi Note 6 Pro', 'Redmi Note 7', 'Redmi Note 8', 'Redmi Note 8 Pro',
    'Redmi Note 9', 'Redmi Note 9S', 'Redmi Note 9 Pro',
    'Redmi Note 10', 'Redmi Note 10S', 'Redmi Note 10 Pro',
    'Redmi Note 11', 'Redmi Note 11S', 'Redmi Note 11 Pro',
    'Redmi Note 12', 'Redmi Note 12S', 'Redmi Note 12 Pro', 'Redmi Note 12 Pro+',
    'Redmi Note 13', 'Redmi Note 13 Pro', 'Redmi Note 13 Pro+',
    'Redmi Note 14', 'Redmi Note 14 Pro', 'Redmi Note 15 Pro+', 'Redmi Note 16',
    'Redmi 13C',
    'Redmi K20', 'Redmi K20 Pro', 'Redmi K30', 'Redmi K30 Pro',
    'Redmi K40', 'Redmi K40 Pro', 'Redmi K50', 'Redmi K50 Pro',
    'Redmi K60', 'Redmi K60 Pro', 'Redmi K70', 'Redmi K70 Pro',
    'Redmi K80', 'Redmi K80 Pro', 'Redmi K90', 'Redmi K90 Pro', 'Redmi K100',
    'POCO F1 (Pocophone F1)', 'POCO F2 Pro', 'POCO F4', 'POCO F5', 'POCO F6', 'POCO F7',
    'POCO X2', 'POCO X3', 'POCO X3 Pro', 'POCO X4', 'POCO X4 Pro',
    'POCO X5', 'POCO X5 Pro', 'POCO X6', 'POCO X6 Pro',
    'POCO X7', 'POCO X7 Pro', 'POCO X8 Pro', 'POCO X8 Pro Max',
    'POCO M2', 'POCO M3', 'POCO M4', 'POCO M5', 'POCO M6', 'POCO M7',
    'POCO C31', 'POCO C40', 'POCO C50', 'POCO C61', 'POCO C71',
    'Khác',
  ],
  OPPO: [
    'OPPO Find X', 'OPPO Find X2', 'OPPO Find X2 Pro',
    'OPPO Find X3', 'OPPO Find X3 Pro',
    'OPPO Find X5', 'OPPO Find X5 Pro',
    'OPPO Find X6', 'OPPO Find X6 Pro',
    'OPPO Find X7', 'OPPO Find X7 Ultra',
    'OPPO Find X8', 'OPPO Find X8 Pro',
    'OPPO Find X9', 'OPPO Find X9 Pro',
    'OPPO Find N', 'OPPO Find N2', 'OPPO Find N2 Flip',
    'OPPO Find N3', 'OPPO Find N3 Flip',
    'OPPO Find N5', 'OPPO Find N6',
    'OPPO Reno', 'OPPO Reno 2', 'OPPO Reno 3', 'OPPO Reno 4', 'OPPO Reno 5',
    'OPPO Reno 6', 'OPPO Reno 7', 'OPPO Reno 8', 'OPPO Reno 9',
    'OPPO Reno 10', 'OPPO Reno 10 Pro',
    'OPPO Reno 11', 'OPPO Reno 11 Pro',
    'OPPO Reno 12', 'OPPO Reno 12 Pro',
    'OPPO Reno 13', 'OPPO Reno 13 Pro',
    'OPPO Reno 14', 'OPPO Reno 15 5G',
    'OPPO A18', 'OPPO A38', 'OPPO A52', 'OPPO A53', 'OPPO A54', 'OPPO A55',
    'OPPO A57', 'OPPO A58', 'OPPO A74', 'OPPO A76', 'OPPO A77', 'OPPO A78',
    'OPPO A94', 'OPPO A6 Pro',
    'OPPO F11', 'OPPO F17', 'OPPO F19', 'OPPO F21', 'OPPO F23', 'OPPO F27', 'OPPO F31',
    'OPPO K3', 'OPPO K5', 'OPPO K7', 'OPPO K9', 'OPPO K10', 'OPPO K12', 'OPPO K14',
    'Khác',
  ],
  Vivo: [
    'vivo X7', 'vivo NEX', 'vivo NEX S',
    'vivo X50', 'vivo X50 Pro', 'vivo X60', 'vivo X60 Pro', 'vivo X60 Pro+',
    'vivo X70', 'vivo X70 Pro', 'vivo X70 Pro+',
    'vivo X80', 'vivo X80 Pro', 'vivo X90', 'vivo X90 Pro', 'vivo X90 Pro+',
    'vivo X100', 'vivo X100 Pro', 'vivo X100 Ultra',
    'vivo X200', 'vivo X200 Pro', 'vivo X200 Ultra',
    'vivo X300', 'vivo X300 Pro',
    'vivo X Fold', 'vivo X Fold 2', 'vivo X Fold 3', 'vivo X Fold 3 Pro', 'vivo X Fold 5',
    'vivo V1', 'vivo V3', 'vivo V5', 'vivo V7', 'vivo V9', 'vivo V11', 'vivo V15',
    'vivo V17', 'vivo V19', 'vivo V20', 'vivo V21', 'vivo V23', 'vivo V25',
    'vivo V27', 'vivo V27e', 'vivo V29', 'vivo V29e',
    'vivo V30', 'vivo V30 Pro', 'vivo V40', 'vivo V40 Pro',
    'vivo V50', 'vivo V50 Pro', 'vivo V60', 'vivo V70',
    'vivo Y51', 'vivo Y52', 'vivo Y53', 'vivo Y55', 'vivo Y66', 'vivo Y68', 'vivo Y72',
    'vivo Y200 5G', 'vivo Y300', 'vivo Y400',
    'iQOO 12', 'iQOO 13', 'iQOO Neo 7', 'iQOO Neo 9', 'iQOO Z6 Pro',
    'Khác',
  ],
  Huawei: [
    'Huawei P9', 'Huawei P10', 'Huawei P20', 'Huawei P20 Pro',
    'Huawei P30', 'Huawei P30 Pro',
    'Huawei P40', 'Huawei P40 Pro',
    'Huawei P50', 'Huawei P50 Pro',
    'Huawei P60', 'Huawei P60 Pro',
    'Huawei Pura 70', 'Huawei Pura 70 Pro', 'Huawei Pura 70 Ultra',
    'Huawei Pura 80', 'Huawei Pura 80 Pro',
    'Huawei Mate 9', 'Huawei Mate 10', 'Huawei Mate 20', 'Huawei Mate 20 Pro',
    'Huawei Mate 30', 'Huawei Mate 30 Pro',
    'Huawei Mate 40', 'Huawei Mate 40 Pro',
    'Huawei Mate 50', 'Huawei Mate 50 Pro',
    'Huawei Mate 60', 'Huawei Mate 60 Pro',
    'Huawei Mate 70', 'Huawei Mate 70 Pro',
    'Huawei Mate 80', 'Huawei Mate 80 Pro',
    'Huawei Mate X', 'Huawei Mate X2', 'Huawei Mate X3', 'Huawei Mate X5', 'Huawei Mate X6',
    'Huawei Mate XT (Gập 3)',
    'Huawei Nova 12', 'Huawei Nova 12 Pro',
    'Khác',
  ],
  Realme: [
    'realme 1', 'realme 2', 'realme 3', 'realme 5', 'realme 6', 'realme 7',
    'realme 8', 'realme 9', 'realme 10', 'realme 11',
    'realme 12', 'realme 12 Pro', 'realme 12 Pro+',
    'realme 13', 'realme 13 Pro+',
    'realme 15', 'realme 16 Pro',
    'realme GT', 'realme GT 2', 'realme GT 2 Pro', 'realme GT 3',
    'realme GT Neo 3', 'realme GT Neo 5', 'realme GT 5',
    'realme GT 6', 'realme GT Neo 6', 'realme GT 7', 'realme GT7 Pro',
    'realme C55', 'realme C65', 'realme C67',
    'realme Narzo 70',
    'realme P4 Power',
    'Khác',
  ],
  OnePlus: [
    'OnePlus 3', 'OnePlus 3T', 'OnePlus 5', 'OnePlus 5T',
    'OnePlus 6', 'OnePlus 6T',
    'OnePlus 7', 'OnePlus 7T', 'OnePlus 7 Pro', 'OnePlus 7T Pro',
    'OnePlus 8', 'OnePlus 8 Pro', 'OnePlus 8T',
    'OnePlus 9', 'OnePlus 9 Pro', 'OnePlus 9R',
    'OnePlus 10', 'OnePlus 10 Pro', 'OnePlus 10T',
    'OnePlus 11', 'OnePlus 11R',
    'OnePlus 12', 'OnePlus 12R',
    'OnePlus 13', 'OnePlus 14 Pro', 'OnePlus 15',
    'OnePlus Open',
    'OnePlus Nord N10', 'OnePlus Nord N20', 'OnePlus Nord N100',
    'OnePlus Nord N200', 'OnePlus Nord N300',
    'OnePlus Nord CE', 'OnePlus Nord CE 2', 'OnePlus Nord CE 3', 'OnePlus Nord CE 4',
    'OnePlus Nord 4',
    'Khác',
  ],
  Motorola: [
    'Moto G4', 'Moto G5', 'Moto G6', 'Moto G7', 'Moto G8', 'Moto G9',
    'Moto G10', 'Moto G30', 'Moto G50', 'Moto G51', 'Moto G52', 'Moto G53',
    'Moto G54', 'Moto G60', 'Moto G62', 'Moto G72', 'Moto G82',
    'Moto G84', 'Moto G85', 'Moto G96', 'Moto G17',
    'Motorola Razr 2019', 'Motorola Razr 5G',
    'Motorola Razr 40', 'Motorola Razr 40 Ultra',
    'Motorola Razr 50', 'Motorola Razr 50 Ultra',
    'Motorola Razr 60', 'Motorola Razr 70 Ultra',
    'Motorola Edge 20', 'Motorola Edge 30', 'Motorola Edge 40',
    'Motorola Edge 50 Fusion', 'Motorola Edge 50 Pro', 'Motorola Edge 50 Ultra',
    'Motorola Edge 60', 'Motorola Edge 70', 'Motorola Edge 70 Fusion',
    'Khác',
  ],
  Sony: [
    'Xperia 1', 'Xperia 1 II', 'Xperia 1 III', 'Xperia 1 IV', 'Xperia 1 V', 'Xperia 1 VI', 'Xperia 1 VII',
    'Xperia 5', 'Xperia 5 II', 'Xperia 5 III', 'Xperia 5 IV', 'Xperia 5 V',
    'Xperia 10', 'Xperia 10 II', 'Xperia 10 III', 'Xperia 10 IV', 'Xperia 10 V', 'Xperia 10 VI', 'Xperia 10 VII',
    'Khác',
  ],
  Nokia: [
    'Nokia C21', 'Nokia C22', 'Nokia C32', 'Nokia C42',
    'Nokia G20', 'Nokia G21', 'Nokia G22', 'Nokia G42',
    'Nokia X20', 'Nokia X30', 'Nokia XR20', 'Nokia XR21',
    'Nokia 9 PureView',
    'HMD Pulse', 'HMD Pulse+', 'HMD Skyline', 'HMD Fusion',
    'Khác',
  ],
  Google: [
    'Pixel 6', 'Pixel 6 Pro', 'Pixel 6a',
    'Pixel 7', 'Pixel 7 Pro', 'Pixel 7a',
    'Pixel 8', 'Pixel 8 Pro', 'Pixel 8a',
    'Pixel 9', 'Pixel 9 Pro', 'Pixel 9 Pro XL', 'Pixel 9 Pro Fold', 'Pixel 9a',
    'Pixel 10', 'Pixel 10 Pro', 'Pixel 10 Pro XL', 'Pixel 10a',
    'Pixel 11', 'Pixel 11 Pro',
    'Khác',
  ],
  Honor: [
    'Honor Magic 5', 'Honor Magic 5 Pro', 'Honor Magic 5 RSR',
    'Honor Magic 6', 'Honor Magic 6 Pro', 'Honor Magic 6 RSR',
    'Honor Magic 8 Pro',
    'Honor Magic V2', 'Honor Magic V3', 'Honor Magic V5', 'Honor Magic V6',
    'Honor Robot Phone',
    'Khác',
  ],
  Nothing: [
    'Nothing Phone 1', 'Nothing Phone 2', 'Nothing Phone 2a',
    'Nothing Phone 3', 'Nothing Phone 3 Pro',
    'Nothing Phone 4a', 'Nothing Phone 4a Pro',
    'Khác',
  ],
  RedMagic: [
    'RedMagic 9', 'RedMagic 9 Pro',
    'RedMagic 10', 'RedMagic 10 Pro',
    'RedMagic 11', 'RedMagic 11 Pro', 'RedMagic 11 Air',
    'Khác',
  ],
  LG: [
    'LG G5', 'LG G6', 'LG G7', 'LG G8',
    'LG V10', 'LG V20', 'LG V30', 'LG V40', 'LG V50', 'LG V50s', 'LG V60',
    'LG Velvet', 'LG Wing',
    'Khác',
  ],
  ASUS: [
    'ASUS ZenFone 3', 'ASUS ZenFone 4', 'ASUS ZenFone 5', 'ASUS ZenFone 6',
    'ASUS ZenFone 7', 'ASUS ZenFone 8', 'ASUS ZenFone 9', 'ASUS ZenFone 10',
    'ASUS ZenFone 11 Ultra', 'ASUS ZenFone 12 Ultra',
    'ASUS ROG Phone', 'ASUS ROG Phone 2', 'ASUS ROG Phone 3',
    'ASUS ROG Phone 5', 'ASUS ROG Phone 6', 'ASUS ROG Phone 7',
    'ASUS ROG Phone 8', 'ASUS ROG Phone 8 Pro',
    'ASUS ROG Phone 9', 'ASUS ROG Phone 9 Pro',
    'Khác',
  ],
  BKAV: ['Bphone B40', 'Bphone B60', 'Bphone B86', 'Khác'],
  Khác: ['Khác'],
};
